/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContaMaxRouteImport } from './routes/conta-max'
import { Route as EspecialistasRouteImport } from './routes/especialistas'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AuthenticatedComissaoCoordenadorRouteImport } from './routes/_authenticated/comissao-coordenador'
import { Route as AuthenticatedComissoesAReceberRouteImport } from './routes/_authenticated/comissoes-a-receber'
import { Route as AuthenticatedComparativoComissaoRouteImport } from './routes/_authenticated/comparativo-comissao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProducaoPorPessoaRouteImport } from './routes/_authenticated/producao-por-pessoa'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedVisaoExecutivaRouteImport } from './routes/_authenticated/visao-executiva'
import { Route as AuthenticatedAdminPosicionamentoRouteImport } from './routes/_authenticated/admin.posicionamento'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedVendasIndexRouteImport } from './routes/_authenticated/vendas.index'
import { Route as AuthenticatedVendasIdRouteImport } from './routes/_authenticated/vendas.$id'
import { Route as AuthenticatedVendasNovaRouteImport } from './routes/_authenticated/vendas.nova'
import { Route as AuthenticatedVendasLancamentoNovaRouteImport } from './routes/_authenticated/vendas.lancamento.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaMaxRoute = ContaMaxRouteImport.update({
  id: '/conta-max',
  path: '/conta-max',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasRoute = EspecialistasRouteImport.update({
  id: '/especialistas',
  path: '/especialistas',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComissaoCoordenadorRoute =
  AuthenticatedComissaoCoordenadorRouteImport.update({
    id: '/comissao-coordenador',
    path: '/comissao-coordenador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesAReceberRoute =
  AuthenticatedComissoesAReceberRouteImport.update({
    id: '/comissoes-a-receber',
    path: '/comissoes-a-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComparativoComissaoRoute =
  AuthenticatedComparativoComissaoRouteImport.update({
    id: '/comparativo-comissao',
    path: '/comparativo-comissao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoPorPessoaRoute =
  AuthenticatedProducaoPorPessoaRouteImport.update({
    id: '/producao-por-pessoa',
    path: '/producao-por-pessoa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisaoExecutivaRoute =
  AuthenticatedVisaoExecutivaRouteImport.update({
    id: '/visao-executiva',
    path: '/visao-executiva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPosicionamentoRoute =
  AuthenticatedAdminPosicionamentoRouteImport.update({
    id: '/admin/posicionamento',
    path: '/admin/posicionamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasIndexRoute =
  AuthenticatedVendasIndexRouteImport.update({
    id: '/vendas/',
    path: '/vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasIdRoute = AuthenticatedVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasNovaRoute = AuthenticatedVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasLancamentoNovaRoute =
  AuthenticatedVendasLancamentoNovaRouteImport.update({
    id: '/vendas/lancamento/nova',
    path: '/vendas/lancamento/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conta-max': typeof ContaMaxRoute
  '/especialistas': typeof EspecialistasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/comissao-coordenador': typeof AuthenticatedComissaoCoordenadorRoute
  '/comissoes-a-receber': typeof AuthenticatedComissoesAReceberRoute
  '/comparativo-comissao': typeof AuthenticatedComparativoComissaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/producao-por-pessoa': typeof AuthenticatedProducaoPorPessoaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/visao-executiva': typeof AuthenticatedVisaoExecutivaRoute
  '/admin/posicionamento': typeof AuthenticatedAdminPosicionamentoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas/': typeof AuthenticatedVendasIndexRoute
  '/vendas/lancamento/nova': typeof AuthenticatedVendasLancamentoNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conta-max': typeof ContaMaxRoute
  '/especialistas': typeof EspecialistasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/comissao-coordenador': typeof AuthenticatedComissaoCoordenadorRoute
  '/comissoes-a-receber': typeof AuthenticatedComissoesAReceberRoute
  '/comparativo-comissao': typeof AuthenticatedComparativoComissaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/producao-por-pessoa': typeof AuthenticatedProducaoPorPessoaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/visao-executiva': typeof AuthenticatedVisaoExecutivaRoute
  '/admin/posicionamento': typeof AuthenticatedAdminPosicionamentoRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/vendas': typeof AuthenticatedVendasIndexRoute
  '/vendas/lancamento/nova': typeof AuthenticatedVendasLancamentoNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/conta-max': typeof ContaMaxRoute
  '/especialistas': typeof EspecialistasRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/comissao-coordenador': typeof AuthenticatedComissaoCoordenadorRoute
  '/_authenticated/comissoes-a-receber': typeof AuthenticatedComissoesAReceberRoute
  '/_authenticated/comparativo-comissao': typeof AuthenticatedComparativoComissaoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/producao-por-pessoa': typeof AuthenticatedProducaoPorPessoaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/visao-executiva': typeof AuthenticatedVisaoExecutivaRoute
  '/_authenticated/admin/posicionamento': typeof AuthenticatedAdminPosicionamentoRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/vendas/$id': typeof AuthenticatedVendasIdRoute
  '/_authenticated/vendas/nova': typeof AuthenticatedVendasNovaRoute
  '/_authenticated/vendas/': typeof AuthenticatedVendasIndexRoute
  '/_authenticated/vendas/lancamento/nova': typeof AuthenticatedVendasLancamentoNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conta-max'
    | '/especialistas'
    | '/redefinir-senha'
    | '/trocar-senha'
    | '/comissao-coordenador'
    | '/comissoes-a-receber'
    | '/comparativo-comissao'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/notificacoes'
    | '/perfil'
    | '/producao-por-pessoa'
    | '/relatorios'
    | '/visao-executiva'
    | '/admin/posicionamento'
    | '/admin/usuarios'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/vendas/'
    | '/vendas/lancamento/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conta-max'
    | '/especialistas'
    | '/redefinir-senha'
    | '/trocar-senha'
    | '/comissao-coordenador'
    | '/comissoes-a-receber'
    | '/comparativo-comissao'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/notificacoes'
    | '/perfil'
    | '/producao-por-pessoa'
    | '/relatorios'
    | '/visao-executiva'
    | '/admin/posicionamento'
    | '/admin/usuarios'
    | '/vendas/$id'
    | '/vendas/nova'
    | '/vendas'
    | '/vendas/lancamento/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/conta-max'
    | '/especialistas'
    | '/redefinir-senha'
    | '/trocar-senha'
    | '/_authenticated/comissao-coordenador'
    | '/_authenticated/comissoes-a-receber'
    | '/_authenticated/comparativo-comissao'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/producao-por-pessoa'
    | '/_authenticated/relatorios'
    | '/_authenticated/visao-executiva'
    | '/_authenticated/admin/posicionamento'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/vendas/$id'
    | '/_authenticated/vendas/nova'
    | '/_authenticated/vendas/'
    | '/_authenticated/vendas/lancamento/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContaMaxRoute: typeof ContaMaxRoute
  EspecialistasRoute: typeof EspecialistasRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-max': {
      id: '/conta-max'
      path: '/conta-max'
      fullPath: '/conta-max'
      preLoaderRoute: typeof ContaMaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas': {
      id: '/especialistas'
      path: '/especialistas'
      fullPath: '/especialistas'
      preLoaderRoute: typeof EspecialistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comissao-coordenador': {
      id: '/_authenticated/comissao-coordenador'
      path: '/comissao-coordenador'
      fullPath: '/comissao-coordenador'
      preLoaderRoute: typeof AuthenticatedComissaoCoordenadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes-a-receber': {
      id: '/_authenticated/comissoes-a-receber'
      path: '/comissoes-a-receber'
      fullPath: '/comissoes-a-receber'
      preLoaderRoute: typeof AuthenticatedComissoesAReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparativo-comissao': {
      id: '/_authenticated/comparativo-comissao'
      path: '/comparativo-comissao'
      fullPath: '/comparativo-comissao'
      preLoaderRoute: typeof AuthenticatedComparativoComissaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao-por-pessoa': {
      id: '/_authenticated/producao-por-pessoa'
      path: '/producao-por-pessoa'
      fullPath: '/producao-por-pessoa'
      preLoaderRoute: typeof AuthenticatedProducaoPorPessoaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-executiva': {
      id: '/_authenticated/visao-executiva'
      path: '/visao-executiva'
      fullPath: '/visao-executiva'
      preLoaderRoute: typeof AuthenticatedVisaoExecutivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/posicionamento': {
      id: '/_authenticated/admin/posicionamento'
      path: '/admin/posicionamento'
      fullPath: '/admin/posicionamento'
      preLoaderRoute: typeof AuthenticatedAdminPosicionamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/': {
      id: '/_authenticated/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AuthenticatedVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/$id': {
      id: '/_authenticated/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof AuthenticatedVendasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/nova': {
      id: '/_authenticated/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AuthenticatedVendasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/lancamento/nova': {
      id: '/_authenticated/vendas/lancamento/nova'
      path: '/vendas/lancamento/nova'
      fullPath: '/vendas/lancamento/nova'
      preLoaderRoute: typeof AuthenticatedVendasLancamentoNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComissaoCoordenadorRoute: typeof AuthenticatedComissaoCoordenadorRoute
  AuthenticatedComissoesAReceberRoute: typeof AuthenticatedComissoesAReceberRoute
  AuthenticatedComparativoComissaoRoute: typeof AuthenticatedComparativoComissaoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProducaoPorPessoaRoute: typeof AuthenticatedProducaoPorPessoaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVisaoExecutivaRoute: typeof AuthenticatedVisaoExecutivaRoute
  AuthenticatedAdminPosicionamentoRoute: typeof AuthenticatedAdminPosicionamentoRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedVendasIdRoute: typeof AuthenticatedVendasIdRoute
  AuthenticatedVendasNovaRoute: typeof AuthenticatedVendasNovaRoute
  AuthenticatedVendasIndexRoute: typeof AuthenticatedVendasIndexRoute
  AuthenticatedVendasLancamentoNovaRoute: typeof AuthenticatedVendasLancamentoNovaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComissaoCoordenadorRoute: AuthenticatedComissaoCoordenadorRoute,
  AuthenticatedComissoesAReceberRoute: AuthenticatedComissoesAReceberRoute,
  AuthenticatedComparativoComissaoRoute: AuthenticatedComparativoComissaoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProducaoPorPessoaRoute: AuthenticatedProducaoPorPessoaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVisaoExecutivaRoute: AuthenticatedVisaoExecutivaRoute,
  AuthenticatedAdminPosicionamentoRoute: AuthenticatedAdminPosicionamentoRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedVendasIdRoute: AuthenticatedVendasIdRoute,
  AuthenticatedVendasNovaRoute: AuthenticatedVendasNovaRoute,
  AuthenticatedVendasIndexRoute: AuthenticatedVendasIndexRoute,
  AuthenticatedVendasLancamentoNovaRoute:
    AuthenticatedVendasLancamentoNovaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContaMaxRoute: ContaMaxRoute,
  EspecialistasRoute: EspecialistasRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
