-- Posicionamento territorial dos corretores e vitrine publica de especialistas.
-- A vitrine nunca consulta profiles diretamente: as RPCs abaixo devolvem somente
-- nome, foto, WhatsApp e regioes de quem deu consentimento explicito.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS public_profile_enabled boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.positioning_regions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade text NOT NULL,
  zona text,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'bairro'
    CHECK (tipo IN ('bairro', 'condominio', 'cidade', 'grupo')),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT positioning_regions_unique UNIQUE (cidade, nome, tipo)
);

CREATE TABLE IF NOT EXISTS public.corretor_positioning_regions (
  corretor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  region_id bigint NOT NULL REFERENCES public.positioning_regions(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (corretor_id, region_id)
);

CREATE INDEX IF NOT EXISTS idx_corretor_positioning_regions_region
  ON public.corretor_positioning_regions(region_id, corretor_id);

ALTER TABLE public.positioning_regions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_positioning_regions ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.positioning_regions TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.corretor_positioning_regions TO authenticated;
GRANT ALL ON public.positioning_regions, public.corretor_positioning_regions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.positioning_regions_id_seq TO authenticated, service_role;

CREATE POLICY positioning_regions_authenticated_select
  ON public.positioning_regions FOR SELECT TO authenticated
  USING (ativo OR public.has_any_role((SELECT auth.uid()), ARRAY['admin','super_admin']::public.app_role[]));

CREATE POLICY positioning_regions_admin_write
  ON public.positioning_regions FOR ALL TO authenticated
  USING (public.has_any_role((SELECT auth.uid()), ARRAY['admin','super_admin']::public.app_role[]))
  WITH CHECK (public.has_any_role((SELECT auth.uid()), ARRAY['admin','super_admin']::public.app_role[]));

CREATE POLICY corretor_positioning_self_select
  ON public.corretor_positioning_regions FOR SELECT TO authenticated
  USING (
    corretor_id = (SELECT auth.uid())
    OR public.has_any_role((SELECT auth.uid()), ARRAY['admin','super_admin']::public.app_role[])
  );

CREATE POLICY corretor_positioning_self_insert
  ON public.corretor_positioning_regions FOR INSERT TO authenticated
  WITH CHECK (
    corretor_id = (SELECT auth.uid())
    AND public.is_active_user((SELECT auth.uid()))
    AND public.has_role((SELECT auth.uid()), 'corretor'::public.app_role)
  );

CREATE POLICY corretor_positioning_self_delete
  ON public.corretor_positioning_regions FOR DELETE TO authenticated
  USING (
    corretor_id = (SELECT auth.uid())
    OR public.has_any_role((SELECT auth.uid()), ARRAY['admin','super_admin']::public.app_role[])
  );

CREATE OR REPLACE FUNCTION public.save_my_positioning(
  _region_ids bigint[],
  _public_enabled boolean
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _user uuid := auth.uid();
BEGIN
  IF _user IS NULL OR NOT public.is_active_user(_user)
    OR NOT public.has_role(_user, 'corretor'::public.app_role) THEN
    RAISE EXCEPTION 'Apenas corretores ativos podem editar o posicionamento.';
  END IF;

  IF coalesce(cardinality(_region_ids), 0) > 20 THEN
    RAISE EXCEPTION 'Selecione no maximo 20 regioes.';
  END IF;

  IF _public_enabled AND NOT EXISTS (
    SELECT 1 FROM public.profiles p
    WHERE p.id = _user
      AND nullif(trim(p.nome), '') IS NOT NULL
      AND nullif(regexp_replace(coalesce(p.telefone, ''), '\D', '', 'g'), '') IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'Preencha nome e telefone antes de publicar seu perfil.';
  END IF;

  IF _public_enabled AND coalesce(cardinality(_region_ids), 0) = 0 THEN
    RAISE EXCEPTION 'Selecione pelo menos uma regiao antes de publicar seu perfil.';
  END IF;

  IF EXISTS (
    SELECT 1 FROM unnest(coalesce(_region_ids, ARRAY[]::bigint[])) requested(id)
    LEFT JOIN public.positioning_regions r ON r.id = requested.id AND r.ativo
    WHERE r.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Uma das regioes selecionadas nao esta disponivel.';
  END IF;

  DELETE FROM public.corretor_positioning_regions WHERE corretor_id = _user;
  INSERT INTO public.corretor_positioning_regions (corretor_id, region_id)
  SELECT _user, requested.id
  FROM unnest(coalesce(_region_ids, ARRAY[]::bigint[])) AS requested(id)
  GROUP BY requested.id;

  UPDATE public.profiles
  SET public_profile_enabled = _public_enabled
  WHERE profiles.id = _user;
END;
$$;

CREATE OR REPLACE FUNCTION public.list_public_positioning_regions()
RETURNS TABLE (id bigint, cidade text, zona text, nome text, tipo text, corretores bigint)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    r.id,
    r.cidade,
    r.zona,
    r.nome,
    r.tipo,
    count(DISTINCT p.id)::bigint AS corretores
  FROM public.positioning_regions r
  LEFT JOIN public.corretor_positioning_regions c ON c.region_id = r.id
  LEFT JOIN public.profiles p
    ON p.id = c.corretor_id
    AND p.ativo
    AND p.public_profile_enabled
    AND nullif(regexp_replace(coalesce(p.telefone, ''), '\D', '', 'g'), '') IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = p.id AND ur.role = 'corretor'::public.app_role
    )
  WHERE r.ativo
  GROUP BY r.id, r.cidade, r.zona, r.nome, r.tipo
  ORDER BY r.cidade, r.zona NULLS LAST, r.nome;
$$;

CREATE OR REPLACE FUNCTION public.list_public_specialists(
  _search text DEFAULT NULL,
  _region_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  nome text,
  avatar_url text,
  telefone text,
  regioes jsonb
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    p.id,
    p.nome,
    p.avatar_url,
    p.telefone,
    jsonb_agg(
      jsonb_build_object(
        'id', r.id,
        'nome', r.nome,
        'cidade', r.cidade,
        'zona', r.zona,
        'tipo', r.tipo
      ) ORDER BY r.cidade, r.nome
    ) AS regioes
  FROM public.profiles p
  JOIN public.corretor_positioning_regions c ON c.corretor_id = p.id
  JOIN public.positioning_regions r ON r.id = c.region_id AND r.ativo
  WHERE p.ativo
    AND p.public_profile_enabled
    AND nullif(regexp_replace(coalesce(p.telefone, ''), '\D', '', 'g'), '') IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = p.id AND ur.role = 'corretor'::public.app_role
    )
    AND (
      _region_id IS NULL
      OR EXISTS (
        SELECT 1 FROM public.corretor_positioning_regions cf
        WHERE cf.corretor_id = p.id AND cf.region_id = _region_id
      )
    )
    AND (
      nullif(trim(_search), '') IS NULL
      OR p.nome ILIKE '%' || trim(_search) || '%'
      OR EXISTS (
        SELECT 1
        FROM public.corretor_positioning_regions cs
        JOIN public.positioning_regions rs ON rs.id = cs.region_id
        WHERE cs.corretor_id = p.id
          AND (rs.nome ILIKE '%' || trim(_search) || '%' OR rs.cidade ILIKE '%' || trim(_search) || '%')
      )
    )
  GROUP BY p.id, p.nome, p.avatar_url, p.telefone
  ORDER BY p.nome;
$$;

REVOKE ALL ON FUNCTION public.list_public_positioning_regions() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.list_public_specialists(text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.save_my_positioning(bigint[], boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_public_positioning_regions() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.list_public_specialists(text, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_my_positioning(bigint[], boolean) TO authenticated;

-- Catalogo inicial extraido da planilha Posicionamento 2026. Entradas combinadas
-- foram separadas para manter filtros consistentes.
INSERT INTO public.positioning_regions (cidade, zona, nome, tipo) VALUES
  ('Sorocaba','Norte','Jardim Santa Esmeralda','bairro'),
  ('Sorocaba','Norte','Vila Helena','bairro'),
  ('Sorocaba','Norte','Vila Formosa','bairro'),
  ('Sorocaba','Norte','Jardim Santa Catarina','bairro'),
  ('Sorocaba','Norte','São Guilherme','bairro'),
  ('Sorocaba','Norte','Jardim São Guilherme','bairro'),
  ('Sorocaba','Norte','Ibiti Paço','condominio'),
  ('Sorocaba','Norte','Ibiti Reserva','condominio'),
  ('Sorocaba','Norte','Parada do Alto','bairro'),
  ('Sorocaba','Norte','Vila Gabriel','bairro'),
  ('Sorocaba','Sul','Jardim Paulistano','bairro'),
  ('Sorocaba','Sul','Parque Campolim','bairro'),
  ('Sorocaba','Sul','Vila Independência','bairro'),
  ('Sorocaba','Sul','Portal da Colina','bairro'),
  ('Sorocaba','Sul','Jardim Vergueiro','bairro'),
  ('Sorocaba','Sul','Vila Jardini','bairro'),
  ('Sorocaba','Sul','Campolim','bairro'),
  ('Sorocaba','Sul','Jardim Faculdade','bairro'),
  ('Sorocaba','Sul','Jardim São Carlos','bairro'),
  ('Sorocaba','Sul','Mont Blanc','condominio'),
  ('Sorocaba','Sul','Giverny','condominio'),
  ('Sorocaba','Sul','Santa Maria','condominio'),
  ('Sorocaba','Sul','Alphavilles','grupo'),
  ('Sorocaba','Sul','Saint Patrick','condominio'),
  ('Sorocaba','Sul','Fazenda Imperial','condominio'),
  ('Sorocaba','Sul','Jardim América','bairro'),
  ('Sorocaba','Sul','Jardim Piratininga','bairro'),
  ('Sorocaba','Leste','Jardim Saira','bairro'),
  ('Sorocaba','Leste','Vila Haro','bairro'),
  ('Sorocaba','Leste','Alto da Boa Vista','bairro'),
  ('Sorocaba','Leste','Granja Olga','condominio'),
  ('Sorocaba','Leste','Vila Amato','bairro'),
  ('Sorocaba','Leste','Jardim Gonçalves','bairro'),
  ('Sorocaba','Oeste','Jardim São Paulo','bairro'),
  ('Sorocaba','Oeste','Wanel Ville','bairro'),
  ('Sorocaba','Oeste','Júlio de Mesquita','bairro'),
  ('Sorocaba','Oeste','Jardim Europa','bairro'),
  ('Sorocaba','Oeste','Piazza di Roma','bairro'),
  ('Sorocaba','Oeste','Jardim Guarujá','bairro'),
  ('Sorocaba','Oeste','Cidade Jardim','bairro'),
  ('Sorocaba','Oeste','Vila Barão','bairro'),
  ('Sorocaba','Centro Expandido','Centro','bairro'),
  ('Sorocaba','Éden','Caguaçu','bairro'),
  ('Sorocaba','Éden','Zona Industrial','bairro'),
  ('Votorantim',NULL,'Votorantim','cidade'),
  ('Votorantim',NULL,'Villa Magari','condominio'),
  ('Votorantim',NULL,'Icatú','condominio'),
  ('Votorantim',NULL,'Villa Flora','condominio'),
  ('Votorantim',NULL,'Belvedere 2','condominio'),
  ('Capela do Alto',NULL,'Capela do Alto','cidade'),
  ('Araçoiaba da Serra',NULL,'Araçoiaba da Serra','cidade')
ON CONFLICT (cidade, nome, tipo) DO UPDATE
SET zona = EXCLUDED.zona, ativo = true;
