-- Auditoria e proteção contra replay para a ponte de leitura do MAX.
-- Não concede leitura nova das tabelas de negócio a anon/authenticated.
CREATE TABLE IF NOT EXISTS public.max_read_bridge_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nonce text NOT NULL UNIQUE,
  operation text NOT NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  result_count integer,
  success boolean NOT NULL DEFAULT false
);

ALTER TABLE public.max_read_bridge_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.max_read_bridge_audit FROM anon, authenticated;
GRANT ALL ON public.max_read_bridge_audit TO service_role;

CREATE INDEX IF NOT EXISTS max_read_bridge_audit_requested_at_idx
  ON public.max_read_bridge_audit (requested_at DESC);

COMMENT ON TABLE public.max_read_bridge_audit IS
  'Auditoria mínima da ponte de leitura do MAX; sem payload, PII ou segredos.';
